title: "[announcement] "
labels: []
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
    validations:
      required: true
  - type: textarea
    id: action
    attributes:
      label: User action
      description: Include an action when the change affects current users
    validations:
      required: false
